In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [5]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [6]:
type(array1)

numpy.ndarray

In [10]:
array1.shape

(4,)

In [9]:
array1.ndim

1

In [11]:
array1.size

4

In [13]:
array1 = np.array([[1,2,3,4],[1,2,3,4]])
array1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
randAr = np.random.rand(3,3,3)

In [15]:
randAr

array([[[0.82027248, 0.32348121, 0.15887515],
        [0.07036133, 0.73776627, 0.3467061 ],
        [0.1612529 , 0.53792613, 0.96176786]],

       [[0.92306026, 0.77414395, 0.88551904],
        [0.84856667, 0.37884606, 0.51092483],
        [0.52367384, 0.95810927, 0.56524684]],

       [[0.44995452, 0.84631905, 0.28662855],
        [0.67903034, 0.50919948, 0.49716474],
        [0.24425823, 0.44217029, 0.68726748]]])

In [17]:
zeroes = np.zeros((2,3,4))

In [18]:
zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
full = np.full((2,3,4),3)

In [20]:
full

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [21]:
randAr[0]

array([[0.82027248, 0.32348121, 0.15887515],
       [0.07036133, 0.73776627, 0.3467061 ],
       [0.1612529 , 0.53792613, 0.96176786]])

In [22]:
randAr[0:2]

array([[[0.82027248, 0.32348121, 0.15887515],
        [0.07036133, 0.73776627, 0.3467061 ],
        [0.1612529 , 0.53792613, 0.96176786]],

       [[0.92306026, 0.77414395, 0.88551904],
        [0.84856667, 0.37884606, 0.51092483],
        [0.52367384, 0.95810927, 0.56524684]]])

In [27]:
randAr1 = np.random.rand(3,4,2)
randAr2 = np.random.rand(3,4,2)

In [28]:
randAr2

array([[[0.48601249, 0.12171247],
        [0.08224551, 0.82294822],
        [0.41372306, 0.3118967 ],
        [0.93751739, 0.71095298]],

       [[0.05567488, 0.07593917],
        [0.42196107, 0.67771596],
        [0.16688485, 0.45499574],
        [0.04432105, 0.1244991 ]],

       [[0.11042137, 0.0866284 ],
        [0.44782674, 0.65969028],
        [0.76483514, 0.54150828],
        [0.72568988, 0.87767293]]])

In [29]:
a3 = np.add(randAr2,randAr1)

In [30]:
a3

array([[[1.47517336, 0.61185102],
        [0.19575217, 0.82917864],
        [0.84950142, 0.40557633],
        [1.83562487, 0.89657833]],

       [[0.75254976, 0.36601239],
        [0.87542671, 0.72619861],
        [0.92023285, 1.12327816],
        [0.51938378, 0.51071908]],

       [[0.89826295, 0.16650051],
        [1.23589905, 1.02707284],
        [0.88107561, 1.34189865],
        [1.56823035, 1.50790637]]])

In [31]:
a3[1][1][1] = 3
a3

array([[[1.47517336, 0.61185102],
        [0.19575217, 0.82917864],
        [0.84950142, 0.40557633],
        [1.83562487, 0.89657833]],

       [[0.75254976, 0.36601239],
        [0.87542671, 3.        ],
        [0.92023285, 1.12327816],
        [0.51938378, 0.51071908]],

       [[0.89826295, 0.16650051],
        [1.23589905, 1.02707284],
        [0.88107561, 1.34189865],
        [1.56823035, 1.50790637]]])

In [32]:
a3.sort()
a3

array([[[0.61185102, 1.47517336],
        [0.19575217, 0.82917864],
        [0.40557633, 0.84950142],
        [0.89657833, 1.83562487]],

       [[0.36601239, 0.75254976],
        [0.87542671, 3.        ],
        [0.92023285, 1.12327816],
        [0.51071908, 0.51938378]],

       [[0.16650051, 0.89826295],
        [1.02707284, 1.23589905],
        [0.88107561, 1.34189865],
        [1.50790637, 1.56823035]]])

In [35]:
on = np.ones((2,3,4))

In [36]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
app = np.append(zeroes,on,axis=0)

In [40]:
app

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
app = np.append(zeroes,on,axis=1)

In [42]:
app

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [44]:
iserted_arry = np.insert(zeroes,1,on,axis=0)

In [47]:
aary_del = np.random.rand(2,3,4)

In [48]:
aary_del

array([[[0.08320935, 0.80076845, 0.12869851, 0.32467051],
        [0.4536042 , 0.33107929, 0.29985307, 0.74088185],
        [0.6792085 , 0.60617078, 0.08945905, 0.18854771]],

       [[0.91267675, 0.08508822, 0.01812347, 0.54275255],
        [0.60653547, 0.59621522, 0.88010145, 0.82700315],
        [0.01226538, 0.23495695, 0.54245527, 0.16040315]]])

In [49]:
np.delete(aary_del,0,axis=1)

array([[[0.4536042 , 0.33107929, 0.29985307, 0.74088185],
        [0.6792085 , 0.60617078, 0.08945905, 0.18854771]],

       [[0.60653547, 0.59621522, 0.88010145, 0.82700315],
        [0.01226538, 0.23495695, 0.54245527, 0.16040315]]])

In [50]:
np.save("new-arry",aary_del)